
--
-- CLIENT
--
  CREATE TABLE "CLIENT" 
   (	"CLIENT_ID" NUMBER(*,0),
	"FIRST_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"CNP" NUMBER NOT NULL ENABLE,
	"BIRTH_DAY" VARCHAR2(20) NOT NULL ENABLE,
	"GENDER" VARCHAR2(20) NOT NULL ENABLE,
	CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CNP") ENABLE
   );
--
-- COUNTRY_ID
--
  CREATE TABLE "COUNTRY_ID" 
   (	"COUNTRY_ID" NUMBER NOT NULL ENABLE,
	"STREET_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"STREET_NUMBER" NUMBER NOT NULL ENABLE,
	CONSTRAINT "COUNTRY_ID_PK" PRIMARY KEY ("COUNTRY_ID") ENABLE
   );
--
-- MD_APPLICATIONFILES
--
  CREATE TABLE "MD_APPLICATIONFILES" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"APPLICATIONS_ID_FK" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"URI" VARCHAR2(4000) NOT NULL ENABLE,
	"TYPE" VARCHAR2(100) NOT NULL ENABLE,
	"STATE" VARCHAR2(100) NOT NULL ENABLE,
	"LANGUAGE" VARCHAR2(100),
	"LOC" NUMBER,
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(4000),
	"UPDATED_ON" DATE,
	"UPDATED_BY" VARCHAR2(4000),
	CONSTRAINT "MD_APPLICATIONFILES_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_APPLICATIONS
--
  CREATE TABLE "MD_APPLICATIONS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(4000),
	"DESCRIPTION" VARCHAR2(4000),
	"BASE_DIR" VARCHAR2(4000),
	"OUTPUT_DIR" VARCHAR2(4000),
	"BACKUP_DIR" VARCHAR2(4000),
	"INPLACE" NUMBER,
	"PROJECT_ID_FK" NUMBER NOT NULL ENABLE,
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_APPLICATIONS_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_CATALOGS
--
  CREATE TABLE "MD_CATALOGS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"CONNECTION_ID_FK" NUMBER NOT NULL ENABLE,
	"CATALOG_NAME" VARCHAR2(4000),
	"DUMMY_FLAG" CHAR(1) DEFAULT 'N',
	"NATIVE_SQL" CLOB,
	"NATIVE_KEY" VARCHAR2(4000),
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_CATALOGS_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_COLUMNS
--
  CREATE TABLE "MD_COLUMNS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"TABLE_ID_FK" NUMBER NOT NULL ENABLE,
	"COLUMN_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"COLUMN_ORDER" NUMBER NOT NULL ENABLE,
	"COLUMN_TYPE" VARCHAR2(4000),
	"PRECISION" NUMBER,
	"SCALE" NUMBER,
	"NULLABLE" CHAR(1) NOT NULL ENABLE,
	"DEFAULT_VALUE" VARCHAR2(4000),
	"NATIVE_SQL" CLOB,
	"NATIVE_KEY" VARCHAR2(4000),
	"DATATYPE_TRANSFORMED_FLAG" CHAR(1),
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	CONSTRAINT "MD_COLUMNS_NULLABLE_Y_N" CHECK ((UPPER(NULLABLE) IN ('Y','N'))) ENABLE,
	CONSTRAINT "MD_COLUMNS_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_CONNECTIONS
--
  CREATE TABLE "MD_CONNECTIONS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"PROJECT_ID_FK" NUMBER NOT NULL ENABLE,
	"TYPE" VARCHAR2(4000),
	"HOST" VARCHAR2(4000),
	"PORT" NUMBER,
	"USERNAME" VARCHAR2(4000),
	"PASSWORD" VARCHAR2(4000),
	"DBURL" VARCHAR2(4000),
	"NAME" VARCHAR2(255),
	"NATIVE_SQL" CLOB,
	"STATUS" VARCHAR2(30),
	"NUM_CATALOGS" NUMBER,
	"NUM_COLUMNS" NUMBER,
	"NUM_CONSTRAINTS" NUMBER,
	"NUM_GROUPS" NUMBER,
	"NUM_ROLES" NUMBER,
	"NUM_INDEXES" NUMBER,
	"NUM_OTHER_OBJECTS" NUMBER,
	"NUM_PACKAGES" NUMBER,
	"NUM_PRIVILEGES" NUMBER,
	"NUM_SCHEMAS" NUMBER,
	"NUM_SEQUENCES" NUMBER,
	"NUM_STORED_PROGRAMS" NUMBER,
	"NUM_SYNONYMS" NUMBER,
	"NUM_TABLES" NUMBER,
	"NUM_TABLESPACES" NUMBER,
	"NUM_TRIGGERS" NUMBER,
	"NUM_USER_DEFINED_DATA_TYPES" NUMBER,
	"NUM_USERS" NUMBER,
	"NUM_VIEWS" NUMBER,
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_CONNECTIONS_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_PACKAGES
--
  CREATE TABLE "MD_PACKAGES" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"SCHEMA_ID_FK" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"PACKAGE_HEADER" CLOB,
	"NATIVE_SQL" CLOB,
	"NATIVE_KEY" VARCHAR2(4000),
	"LANGUAGE" VARCHAR2(40) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_PACKAGES_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_PRIVILEGES
--
  CREATE TABLE "MD_PRIVILEGES" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"SCHEMA_ID_FK" NUMBER NOT NULL ENABLE,
	"PRIVILEGE_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"PRIVELEGE_OBJECT_ID" NUMBER,
	"PRIVELEGEOBJECTTYPE" VARCHAR2(4000) NOT NULL ENABLE,
	"PRIVELEGE_TYPE" VARCHAR2(4000) NOT NULL ENABLE,
	"ADMIN_OPTION" CHAR(1),
	"NATIVE_SQL" CLOB NOT NULL ENABLE,
	"NATIVE_KEY" VARCHAR2(4000),
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_PRIVILEGES_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_PROJECTS
--
  CREATE TABLE "MD_PROJECTS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"PROJECT_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_PROJECTS_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_SCHEMAS
--
  CREATE TABLE "MD_SCHEMAS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"CATALOG_ID_FK" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(4000),
	"TYPE" CHAR(1),
	"CHARACTER_SET" VARCHAR2(4000),
	"VERSION_TAG" VARCHAR2(40),
	"NATIVE_SQL" CLOB,
	"NATIVE_KEY" VARCHAR2(4000),
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_SCHEMAS_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MD_TABLES
--
  CREATE TABLE "MD_TABLES" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"SCHEMA_ID_FK" NUMBER NOT NULL ENABLE,
	"TABLE_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"NATIVE_SQL" CLOB,
	"NATIVE_KEY" VARCHAR2(4000),
	"QUALIFIED_NATIVE_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MD_TABLES_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- MIGR_DATATYPE_TRANSFORM_MAP
--
  CREATE TABLE "MIGR_DATATYPE_TRANSFORM_MAP" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"PROJECT_ID_FK" NUMBER NOT NULL ENABLE,
	"MAP_NAME" VARCHAR2(4000),
	"SECURITY_GROUP_ID" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CREATED_ON" DATE DEFAULT sysdate NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"LAST_UPDATED_ON" DATE,
	"LAST_UPDATED_BY" VARCHAR2(255),
	CONSTRAINT "MIGR_DATATYPE_TRANSFORM_M_PK" PRIMARY KEY ("ID") ENABLE
   );
--
-- P_FACILITY
--
  CREATE TABLE "P_FACILITY" 
   (	"FACILITY_ID" NUMBER(*,0) NOT NULL ENABLE,
	"TV_CABLE" VARCHAR2(20) DEFAULT 'NO' NOT NULL ENABLE,
	"POOL" VARCHAR2(20) DEFAULT 'NO' NOT NULL ENABLE,
	"GARDEN" VARCHAR2(20) DEFAULT 'NO' NOT NULL ENABLE,
	"ELECTRICITY" VARCHAR2(20) DEFAULT 'NO' NOT NULL ENABLE,
	"FIREPLACE" VARCHAR2(20) DEFAULT 'NO' NOT NULL ENABLE,
	"WASHER" VARCHAR2(20) DEFAULT 'NO' NOT NULL ENABLE,
	"WI_FI" VARCHAR2(20) DEFAULT 'NO' NOT NULL ENABLE,
	"EMPTY_SPACE" VARCHAR2(20) DEFAULT 'YES' NOT NULL ENABLE,
	CONSTRAINT "P_FACILITY_PK" PRIMARY KEY ("FACILITY_ID") ENABLE
   );
--
-- P_LOCATION
--
  CREATE TABLE "P_LOCATION" 
   (	"LOCATION_ID" NUMBER NOT NULL ENABLE,
	"COUNTRY_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"CITY_NAME" VARCHAR2(20),
	"LOCATION_INFO" NUMBER NOT NULL ENABLE,
	CONSTRAINT "PROP_LOCATION_PK" PRIMARY KEY ("LOCATION_ID") ENABLE
   );
--
-- P_STATUS
--
  CREATE TABLE "P_STATUS" 
   (	"STATUS_ID" NUMBER(*,0) NOT NULL ENABLE,
	"RENTED_BY_CLIENT" VARCHAR2(20) DEFAULT NULL,
	"CNTR_SIGNED" DATE,
	"CNTR_EXPIRE" DATE,
	"STATUS_RENT" VARCHAR2(20) DEFAULT 'AVAIBLE',
	CONSTRAINT "PROP_STATUS_PK" PRIMARY KEY ("STATUS_ID") ENABLE
   );
--
-- P_TYPE
--
  CREATE TABLE "P_TYPE" 
   (	"TYPE_ID" NUMBER NOT NULL ENABLE,
	"TYPE_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"PROP_COST" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"PROP_METERS" NUMBER NOT NULL ENABLE,
	CONSTRAINT "PROP_TYPE_PK" PRIMARY KEY ("TYPE_ID") ENABLE
   );
--
-- PROPERTY_INFO
--
  CREATE TABLE "PROPERTY_INFO" 
   (	"PROP_ID" NUMBER(*,0) NOT NULL ENABLE,
	"PROP_LOCATION" NUMBER(*,0) NOT NULL ENABLE,
	"PROP_TYPE" NUMBER(*,0) NOT NULL ENABLE,
	"PROP_FACILITY" NUMBER(*,0) NOT NULL ENABLE,
	"PROP_STATUS" NUMBER(*,0) NOT NULL ENABLE,
	"PROP_OWNER" NUMBER DEFAULT NULL,
	CONSTRAINT "PROPERTY_PK" PRIMARY KEY ("PROP_ID") ENABLE
   );
--
-- CLIENT_PK
--
  CREATE UNIQUE INDEX "CLIENT_PK" ON "CLIENT" ("CNP");
--
-- COUNTRY_ID_PK
--
  CREATE UNIQUE INDEX "COUNTRY_ID_PK" ON "COUNTRY_ID" ("COUNTRY_ID");
--
-- MD_APP_FILE_TYPE_IDX
--
  CREATE INDEX "MD_APP_FILE_TYPE_IDX" ON "MD_APPLICATIONFILES" ("TYPE","ID");
--
-- MD_APPLICATIONFILES_PK
--
  CREATE UNIQUE INDEX "MD_APPLICATIONFILES_PK" ON "MD_APPLICATIONFILES" ("ID");
--
-- MD_APPLICATIONS_PK
--
  CREATE UNIQUE INDEX "MD_APPLICATIONS_PK" ON "MD_APPLICATIONS" ("ID");
--
-- MD_CATALOGS_PK
--
  CREATE UNIQUE INDEX "MD_CATALOGS_PK" ON "MD_CATALOGS" ("ID");
--
-- MD_COLUMNS_PK
--
  CREATE UNIQUE INDEX "MD_COLUMNS_PK" ON "MD_COLUMNS" ("ID");
--
-- MD_CONNECTIONS_PK
--
  CREATE UNIQUE INDEX "MD_CONNECTIONS_PK" ON "MD_CONNECTIONS" ("ID");
--
-- MD_PACKAGES_PK
--
  CREATE UNIQUE INDEX "MD_PACKAGES_PK" ON "MD_PACKAGES" ("ID");
--
-- MD_PRIVILEGES_PK
--
  CREATE UNIQUE INDEX "MD_PRIVILEGES_PK" ON "MD_PRIVILEGES" ("ID");
--
-- MD_PROJECTS_PK
--
  CREATE UNIQUE INDEX "MD_PROJECTS_PK" ON "MD_PROJECTS" ("ID");
--
-- MD_SCHEMAS_PK
--
  CREATE UNIQUE INDEX "MD_SCHEMAS_PK" ON "MD_SCHEMAS" ("ID");
--
-- MD_STATE_TYPE__ID
--
  CREATE INDEX "MD_STATE_TYPE__ID" ON "MD_APPLICATIONFILES" ("STATE","TYPE","ID");
--
-- MD_TABLES_PK
--
  CREATE UNIQUE INDEX "MD_TABLES_PK" ON "MD_TABLES" ("ID");
--
-- MIGR_DATATYPE_TRANSFORM_M_PK
--
  CREATE UNIQUE INDEX "MIGR_DATATYPE_TRANSFORM_M_PK" ON "MIGR_DATATYPE_TRANSFORM_MAP" ("ID");
--
-- P_FACILITY_PK
--
  CREATE UNIQUE INDEX "P_FACILITY_PK" ON "P_FACILITY" ("FACILITY_ID");
--
-- PROP_LOCATION_PK
--
  CREATE UNIQUE INDEX "PROP_LOCATION_PK" ON "P_LOCATION" ("LOCATION_ID");
--
-- PROP_STATUS_PK
--
  CREATE UNIQUE INDEX "PROP_STATUS_PK" ON "P_STATUS" ("STATUS_ID");
--
-- PROP_TYPE_PK
--
  CREATE UNIQUE INDEX "PROP_TYPE_PK" ON "P_TYPE" ("TYPE_ID");
--
-- PROPERTY_PK
--
  CREATE UNIQUE INDEX "PROPERTY_PK" ON "PROPERTY_INFO" ("PROP_ID");
--
-- MD_FILE_APP_FK
--
ALTER TABLE "MD_APPLICATIONFILES" ADD CONSTRAINT "MD_FILE_APP_FK" FOREIGN KEY ("APPLICATIONS_ID_FK") REFERENCES "MD_APPLICATIONS"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_APP_PROJ_FK
--
ALTER TABLE "MD_APPLICATIONS" ADD CONSTRAINT "MD_APP_PROJ_FK" FOREIGN KEY ("PROJECT_ID_FK") REFERENCES "MD_PROJECTS"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_CATALOGS_MD_CONNECTION_FK1
--
ALTER TABLE "MD_CATALOGS" ADD CONSTRAINT "MD_CATALOGS_MD_CONNECTION_FK1" FOREIGN KEY ("CONNECTION_ID_FK") REFERENCES "MD_CONNECTIONS"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_COLUMNS_MD_TABLES_FK1
--
ALTER TABLE "MD_COLUMNS" ADD CONSTRAINT "MD_COLUMNS_MD_TABLES_FK1" FOREIGN KEY ("TABLE_ID_FK") REFERENCES "MD_TABLES"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_CONNECTIONS_MD_PROJECT_FK1
--
ALTER TABLE "MD_CONNECTIONS" ADD CONSTRAINT "MD_CONNECTIONS_MD_PROJECT_FK1" FOREIGN KEY ("PROJECT_ID_FK") REFERENCES "MD_PROJECTS"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_PACKAGES_MD_SCHEMAS_FK1
--
ALTER TABLE "MD_PACKAGES" ADD CONSTRAINT "MD_PACKAGES_MD_SCHEMAS_FK1" FOREIGN KEY ("SCHEMA_ID_FK") REFERENCES "MD_SCHEMAS"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_PRIVILEGES_MD_SCHEMAS_FK1
--
ALTER TABLE "MD_PRIVILEGES" ADD CONSTRAINT "MD_PRIVILEGES_MD_SCHEMAS_FK1" FOREIGN KEY ("SCHEMA_ID_FK") REFERENCES "MD_SCHEMAS"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_SCHEMAS_MD_CATALOGS_FK1
--
ALTER TABLE "MD_SCHEMAS" ADD CONSTRAINT "MD_SCHEMAS_MD_CATALOGS_FK1" FOREIGN KEY ("CATALOG_ID_FK") REFERENCES "MD_CATALOGS"("ID") ON DELETE CASCADE ENABLE;

--
-- MD_TABLES_MD_SCHEMAS_FK1
--
ALTER TABLE "MD_TABLES" ADD CONSTRAINT "MD_TABLES_MD_SCHEMAS_FK1" FOREIGN KEY ("SCHEMA_ID_FK") REFERENCES "MD_SCHEMAS"("ID") ON DELETE CASCADE ENABLE;

--
-- MIGR_DATATYPE_TRANSFORM_M_FK1
--
ALTER TABLE "MIGR_DATATYPE_TRANSFORM_MAP" ADD CONSTRAINT "MIGR_DATATYPE_TRANSFORM_M_FK1" FOREIGN KEY ("PROJECT_ID_FK") REFERENCES "MD_PROJECTS"("ID") ON DELETE CASCADE ENABLE;

--
-- P_LOCATION_FK1
--
ALTER TABLE "P_LOCATION" ADD CONSTRAINT "P_LOCATION_FK1" FOREIGN KEY ("LOCATION_INFO") REFERENCES "COUNTRY_ID"("COUNTRY_ID") ENABLE;

--
-- PROPERTY_INFO_FK1
--
ALTER TABLE "PROPERTY_INFO" ADD CONSTRAINT "PROPERTY_INFO_FK1" FOREIGN KEY ("PROP_OWNER") REFERENCES "CLIENT"("CNP") ENABLE;

--
-- PROPERTY_INFO_FK2
--
ALTER TABLE "PROPERTY_INFO" ADD CONSTRAINT "PROPERTY_INFO_FK2" FOREIGN KEY ("PROP_FACILITY") REFERENCES "P_FACILITY"("FACILITY_ID") ON DELETE CASCADE ENABLE;

--
-- PROPERTY_INFO_FK3
--
ALTER TABLE "PROPERTY_INFO" ADD CONSTRAINT "PROPERTY_INFO_FK3" FOREIGN KEY ("PROP_TYPE") REFERENCES "P_TYPE"("TYPE_ID") ON DELETE CASCADE ENABLE;

--
-- PROPERTY_INFO_FK4
--
ALTER TABLE "PROPERTY_INFO" ADD CONSTRAINT "PROPERTY_INFO_FK4" FOREIGN KEY ("PROP_STATUS") REFERENCES "P_STATUS"("STATUS_ID") ENABLE;

--
-- PROPERTY_INFO_FK5
--
ALTER TABLE "PROPERTY_INFO" ADD CONSTRAINT "PROPERTY_INFO_FK5" FOREIGN KEY ("PROP_LOCATION") REFERENCES "P_LOCATION"("LOCATION_ID") ON DELETE CASCADE ENABLE;

